version: '3.8'
services:
  webserver:
    build:
      context: ./docker/php/${PHP_VERSION}
      dockerfile: dockerFile.php
    container_name: "webserver"
    restart: "always"
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
      - ./docker/logs/apache2:/var/log/apache2
      - ./docker/logs/xdebug:/var/log/xdebug
  database:
    build:
      context: ./docker/database/${DB_TYPE}/${DB_VERSION}
      dockerfile: dockerFile.${DB_TYPE}
    container_name: "dockerFile.${DB_TYPE}"
    restart: "always"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./docker/database/${DB_TYPE}/${DB_VERSION}/initdb:/docker-entrypoint-initdb.d
      - ./docker/logs/${DB_TYPE}:/var/log/{DB_TYPE}
    environment:
      ${DB_VARIABLE_ROOT_PASWORD}: ${DB_ROOT_PASSWORD}
      ${DB_VARIABLE_NAME}: ${DB_NAME}
      ${DB_VARIABLE_USER}: ${DB_USER}
      ${DB_VARIABLE_PASSWORD}: ${DB_PASSWORD}